server:
  port: 8888
  servlet:
    context-path: /hrms

spring:
  application:
    name: Enterprise-HRMS

  datasource:
    druid:
      url: jdbc:mysql://xxx:3306/enterprise_hrms?connectTimeout=5000&socketTimeout=10000&autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: xxx
      password: xxx
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 124.222.118.90
    port: 6379
    password: xxx

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    local-cache-scope: statement

fan:
  jwt:
    header: Authorization
    expire: 259200000

